version: '3'

services:
  mysql-db:
    image: mysql
    ports:
      - 3306
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=codedesignlabs_node
    volumes:
      - mysql-data:/var/lib/mysql
  app:
      build: ./backend/
volumes:
  mysql-data:
    driver: local
