version: '3.8'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=codedesignlabs_node
  app:
      build: .
      network_mode: "host"